// Generates public/third-party-notices.txt, the notice file that Vite copies
// verbatim into dist/ so that every deployed build carries the license texts of
// the code and data it contains.
//
// Run with: npm run notices
//
// The package list below covers the dependencies that actually end up in the
// bundle. Build-time-only tooling (Vite, esbuild, TypeScript, @types/*) is not
// distributed and therefore not listed here; it is described in
// THIRD_PARTY_NOTICES.md instead.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Packages whose code is included in the built site, in notice order. */
const BUNDLED_PACKAGES = [
  'react',
  'react-dom',
  'scheduler',
  'lucide-react',
  'pdf-lib',
  '@pdf-lib/upng',
  '@pdf-lib/standard-fonts',
  'pako',
];

/** License file names used by npm packages, in lookup order. */
const LICENSE_FILES = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'license', 'LICENSE-MIT'];

function readPackage(name) {
  const dir = resolve(root, 'node_modules', name);
  const manifest = JSON.parse(readFileSync(resolve(dir, 'package.json'), 'utf8'));
  const license =
    typeof manifest.license === 'string'
      ? manifest.license
      : (manifest.license?.type ?? 'see license text below');
  let text = null;
  for (const file of LICENSE_FILES) {
    try {
      text = readFileSync(resolve(dir, file), 'utf8').trim();
      break;
    } catch {
      // try the next candidate name
    }
  }
  if (!text) throw new Error(`no license file found for ${name}; install dependencies first`);
  const rawRepository =
    typeof manifest.repository === 'string' ? manifest.repository : manifest.repository?.url;
  const repository =
    manifest.homepage ??
    (rawRepository
      ? rawRepository
          .replace(/^git\+/, '')
          .replace(/^git:\/\//, 'https://')
          .replace(/\.git$/, '')
          .replace(/^([^/]+\/[^/]+)$/, 'https://github.com/$1')
      : undefined);
  return { name, version: manifest.version, license, text, repository };
}

function readLocal(path) {
  return readFileSync(resolve(root, path), 'utf8').trim();
}

function rule(title) {
  return `\n${'-'.repeat(title.length)}\n${title}\n${'-'.repeat(title.length)}\n\n`;
}

const out = [];
out.push(`THIRD-PARTY NOTICES — Calibration Board Studio
=============================================

This file is distributed with the built site (dist/third-party-notices.txt) so
that the notices required by the licenses of the bundled components travel with
it. It is generated by scripts/generate_notices.mjs; edit that script or the
texts in licenses/ instead of this file.

The application code itself is released under the MIT License (see LICENSE in
the repository).

Bundled components
==================
`);

for (const name of BUNDLED_PACKAGES) {
  const pkg = readPackage(name);
  out.push(`\n${'='.repeat(72)}\n${pkg.name} ${pkg.version} — ${pkg.license}\n`);
  if (pkg.repository) out.push(`${pkg.repository.replace(/^git\+/, '').replace(/\.git$/, '')}\n`);
  out.push(`\n${pkg.text}\n`);
}

out.push(`
${'='.repeat(72)}
zlib — Zlib License (pako bundles code derived from zlib)
${'='.repeat(72)}

${readLocal('licenses/Zlib.txt')}
`);

out.push(`

Marker codebook data
====================

src/data/markers.json is generated by scripts/generate_markers.py from the
predefined ArUco and AprilTag dictionaries of OpenCV (https://opencv.org),
which is distributed under the Apache License 2.0. The AprilTag families
themselves come from the APRIL Robotics Laboratory at the University of
Michigan and are redistributed under the BSD 2-Clause License.

${'='.repeat(72)}
OpenCV — Apache License 2.0
${'='.repeat(72)}

${readLocal('licenses/Apache-2.0.txt')}

${'='.repeat(72)}
AprilTag families (tag16h5, tag25h9, tag36h10, tag36h11) — BSD 2-Clause
${'='.repeat(72)}

${readLocal('licenses/AprilTag-BSD-2-Clause.txt')}
`);

const target = resolve(root, 'public/third-party-notices.txt');
mkdirSync(dirname(target), { recursive: true });
const content = out.join('').replace(/\n{4,}/g, '\n\n\n');
writeFileSync(target, content, 'utf8');
console.log(`wrote public/third-party-notices.txt (${content.length} bytes)`);
